# Generated by Django 3.1.5 on 2021-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='langugage',
            new_name='language',
        ),
    ]
